### ISSUE TITLE
没有支持 Release notes，同时 tag 名的命名不灵活

### ISSUE THREAD

**Issue by TokeyJerry** [xiongwilee/gitlab-autotag#3]
1、打 tag 时候我们希望加上描述信息，每个版本修改了是么，所以会添 Release notes，希望可以支持
2、打 tag 的时候我们希望我们的版本号是从 package.json 中获取的 version ，并不希望单纯的用日期。

**Comment by xiongwilee** [comment]
1、2都可以搞

**Comment by xiongwilee** [comment]
https://github.com/xiongwilee/gitlab-autotag/commit/4d4ea5cf4083fab258c77b98c6902c04cd5b3a1e

添加了两个钩子`getTagName`、`getTagMsg`，你可以看下源码自行根据场景需求生成release notes和tag名
